before_install:
- sudo apt-get update -qq
- sudo apt-get install -y pandoc
- sudo apt-get install -y texlive-full
- sudo apt-get install -y texlive-xetex

script:
  - pandoc -o example/bibimbap.html --template template.html --css template.css --metadata image=example/bibimbap.jpg --self-contained example/bibimbap.yaml
  - pandoc -o example/sandbox.html --template template.html --css template.css --self-contained example/sandbox.yaml
