before_install:
- sudo apt-get update -qq
- sudo apt-get install -y wget
- sudo apt-get install -y texlive-full
- sudo apt-get install -y texlive-xetex
- wget https://github.com/jgm/pandoc/releases/download/2.7.2/pandoc-2.7.2-1-amd64.deb
- sudo dpkg -i pandoc-2.7.2-1-amd64.deb

script:
  - pandoc -o example/bibimbap.html --template templates/cuisineaz/index.html --css templates/cuisineaz/index.css --metadata image=example/bibimbap.jpg --self-contained example/bibimbap.yaml
  - pandoc -o example/bibimbap.html --template templates/justonecookbook/index.html --css templates/justonecookbook/index.css --metadata image=example/bibimbap.jpg --self-contained example/bibimbap.yaml
  - pandoc -o example/sandbox.html --template templates/cuisineaz/index.html --css templates/cuisineaz/index.css --self-contained example/sandbox.yaml
  - pandoc -o example/sandbox.html --template templates/justonecookbook/index.html --css templates/justonecookbook/index.css --self-contained example/sandbox.yaml
